-- =============================================================================
-- Handoff - schema location
--
-- The schema is no longer defined here. It lives in db/migrations/, which is
-- the single authoritative source:
--
--     db/migrations/001_create_tables.sql   initial schema
--     db/migrations/0NN_*.sql               subsequent changes
--
-- This file previously held a full copy of the DDL. Keeping both meant two
-- definitions that could silently disagree - the migrations being what the
-- database actually ran, and this file being what people read. The copy is
-- gone rather than left to rot; its content is in 001 and in git history.
--
-- Apply migrations:
--     npm -w @handoff/api run db:migrate
--
-- Inspect the live schema:
--     pg_dump --schema-only "$DATABASE_URL"
--
-- Dump it back to a file, if you want a readable snapshot to diff:
--     pg_dump --schema-only --no-owner --no-privileges "$DATABASE_URL" \
--       > db/schema.generated.sql
-- =============================================================================
